### ISSUE TITLE
Margin and Error Different Depending on Zoom

### ISSUE THREAD

**Issue by npineda** [w8r/polygon-offset#2]
I assume the margin and padding is a meters offset of the original points. If that's correct -I noticed that with the leaflet example if you were to change the zoom both the padding and the margin would change and then go completely crazy if it's too far zoomed out.

**Comment by w8r** [comment]
@npineda Unfortunately, the algorithm is not geodetic (as any other you can find). It takes in margin/padding values in the same units you have in coordinates, so it's not meters. To perform close-to reality offsetting on the map I used reprojections and the geometries positioned closely to the equator. To do it properly you have to perform that kind of operations in equidistant projection. I struggled with this problem here https://github.com/w8r/moscow-rings/
